# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name_plural': '出版社'},
        ),
        migrations.AlterField(
            model_name='publish',
            name='city',
            field=models.CharField(max_length=32, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
    ]
